import { ProjectType, SectionType } from "./store-types";
import * as images from "./store-images";

export const projectsDp: ProjectType[] = [
    {
        caption: "page-qa2",
        description: "QA information website",
        urlGithub: "https://github.com/maxzz/page-qa2",
        urlDemo: "https://maxzz.github.io/page-qa2",
        previewUrl: images.pageQa2,
        localPath: "C:/Y/w/2-web/0-dp/page-qa2",
    },
    {
        caption: "PMIT",
        description: "Password manager investigation tool as an experiment with data-driven user interfaces (D2UI).",
        urlGithub: "https://github.com/maxzz/dropzone",
        urlDemo: "https://maxzz.github.io/dropzone",
        previewUrl: images.previewDropzon,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/dropzone",
    },
    {
        caption: "page-extension-installation",
        description: "Page for installing the DigitalPersona extension.",
        urlGithub: "https://github.com/maxzz/page-extension-installation",
        urlDemo: "https://maxzz.github.io/page-extension-installation",
        previewUrl: images.pageExtensionInstallation,
        localPath: "C:/Y/w/2-web/0-dp/page-extension-installation",
    },
    {
        caption: "test-pm",
        description: "Dynamic webpage to test Password Manager login and password change screens.",
        urlGithub: "https://github.com/maxzz/test-pm",
        urlDemo: "https://maxzz.github.io/test-pm",
        previewUrl: images.testPm,
        localPath: "C:/Y/w/2-web/0-dp/test-pm",
    },
    {
        caption: "test-pm-second",
        description: "Second page for checking logins on the same domain.",
        urlGithub: "https://github.com/maxzz/test-pm-second",
        urlDemo: "https://maxzz.github.io/test-pm-second",
        previewUrl: images.testPmSecond,
        localPath: "C:/Y/w/2-web/0-dp/test-pm-second",
    },
    {
        caption: "test-pm-domain-logins",
        description: "Test multiple logins under the same domain.",
        urlGithub: "https://github.com/maxzz/test-pm-domain-logins",
        urlDemo: "https://maxzz.github.io/test-pm-domain-logins/",
        previewUrl: images.testPmDomainLogins,
        localPath: "C:/Y/w/2-web/0-dp/test-pm-domain-logins",
    },
    {
        caption: "test-pm-domain-logins22",
        description: "Application for testing different login forms and password change in one domain.",
        urlGithub: "https://github.com/maxzz/test-pm-domain-logins22",
        urlDemo: "https://maxzz.github.io/test-pm-domain-logins22",
        previewUrl: images.testPmDomainLogins22,
        localPath: "C:/Y/w/2-web/0-dp/test-pm-domain-logins22",
    },

    // {
    //     caption: "",
    //     description: "",
    //     urlGithub: "",
    //     urlDemo: "",
    //     previewUrl: images.editorsSvgShapes22Template,
    //     localPath: "",
    // },
];

export const projectsUx: ProjectType[] = [
    {
        caption: "color-names22",
        description: "CSS color names selector",
        urlGithub: "https://github.com/maxzz/color-names22",
        urlDemo: "https://maxzz.github.io/color-names22",
        previewUrl: images.colorNames22,
        localPath: "C:/Y/w/2-web/7-my-webpages/color-names22",
    },
    {
        caption: "simple-border-radius22",
        description: "CSS border radius generator",
        urlGithub: "https://github.com/maxzz/simple-border-radius22",
        urlDemo: "https://maxzz.github.io/simple-border-radius22",
        previewUrl: images.simpleBorderRadius,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-border-radius22",
    },
    {
        caption: "border-radius-generator",
        description: "Simplest border radius generator with Vue.js Composition API",
        urlGithub: "https://github.com/maxzz/border-radius-generator",
        urlDemo: "https://maxzz.github.io/border-radius-generator",
        previewUrl: images.borderRadiusGenerator,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-border-radius",
    },
    {
        caption: "red3-curves",
        description: "Examination of the curves D3",
        urlGithub: "https://github.com/maxzz/red3-curves",
        urlDemo: "https://maxzz.github.io/red3-curves",
        previewUrl: images.red3Curves,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-lines",
    },
    {
        caption: "red3-path",
        description: "Curve path simplification",
        urlGithub: "https://github.com/maxzz/red3-path",
        urlDemo: "https://maxzz.github.io/red3-path",
        previewUrl: images.red3Path,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-path/tailwind",
    },
    {
        caption: "red3-voronoi",
        description: "Voronoi algorithm playground",
        urlGithub: "https://github.com/maxzz/red3-voronoi",
        urlDemo: "https://maxzz.github.io/red3-voronoi",
        previewUrl: images.reactD3Voronoi,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-voronoi",
    },
    {
        caption: "react-d3",
        description: "Coexistence of React with D3.js",
        urlGithub: "https://github.com/maxzz/react-d3",
        urlDemo: "https://maxzz.github.io/react-d3",
        previewUrl: images.reactD3,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-red3",
    },
    {
        caption: "svg-path",
        description: "SVG path exploration",
        urlGithub: "https://github.com/maxzz/svg-path",
        urlDemo: "https://maxzz.github.io/svg-path",
        previewUrl: images.svgPath,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/svg-path",
    },
    {
        caption: "quadratic-curves",
        description: "Quadratic curves experiments.",
        urlGithub: "https://github.com/maxzz/quadratic-curves",
        urlDemo: "https://github.com/maxzz/quadratic-curves", // no demo
        previewUrl: images.quadraticCurves,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-bezier/quadratic",
    },
    {
        caption: "ngon-gen22",
        description: "N-gon generator.",
        urlGithub: "https://github.com/maxzz/ngon-gen22",
        urlDemo: "https://maxzz.github.io/ngon-gen22",
        previewUrl: images.ngonGen22,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes22",
    },
    {
        caption: "ngon-gen22-template",
        description: "Template for React, Jotai, TailwindCSS app",
        urlGithub: "https://github.com/maxzz/ngon-gen22-template",
        urlDemo: "https://maxzz.github.io/ngon-gen22",
        previewUrl: images.editorsSvgShapes22Template,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes22-template",
    },
    {
        caption: "cursors",
        description: "Web Cursors Lab",
        urlGithub: "https://github.com/maxzz/cursors",
        urlDemo: "https://maxzz.github.io/cursors",
        previewUrl: images.cursors,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/2-image-processing/cursors",
    },
    {
        caption: "noise-gen",
        description: "Noise generator",
        urlGithub: "https://github.com/maxzz/noise-gen",
        urlDemo: "https://maxzz.github.io/noise-gen",
        previewUrl: images.noiseGen,
        localPath: "C:/Y/w/2-web/7-my-webpages/webworker-noise-gen",
    },
    {
        caption: "css-3d",
        description: "Experimanting with pseudo-3D shapes.",
        urlGithub: "https://github.com/maxzz/css-3d",
        urlDemo: "https://maxzz.github.io/css-3d",
        previewUrl: images.css3d,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-css-3d",
    },
    {
        caption: "react-spring-tests",
        description: "Exploring different use cases for the react-spring library.",
        urlGithub: "https://github.com/maxzz/react-spring-tests",
        urlDemo: "https://maxzz.github.io/react-spring-tests",
        previewUrl: images.reactSpringTests,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/1-animations/react-spring-tests",
    },

    {
        caption: "leva-ui-dynamic-boxes",
        description: "Experimenting with box resizing handles using leva and zustand.",
        urlGithub: "https://github.com/maxzz/leva-ui-dynamic-boxes",
        urlDemo: "https://maxzz.github.io/leva-ui-dynamic-boxes",
        previewUrl: images.levaUiDynamicBoxes,
        localPath: "C:/Y/w/2-web/7-my-webpages/leva-ui-dynamic-boxes",
    },
    {
        caption: "volume-illusion",
        description: "Illusion of three-dimensional shapes.",
        urlGithub: "https://github.com/maxzz/volume-illusion",
        urlDemo: "https://maxzz.github.io/volume-illusion",
        previewUrl: images.volumeIllusion,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-volume-illusion",
    },
    {
        caption: "real-time-resize-rcv",
        description: "Created with CodeSandbox. Virtual lists.",
        urlGithub: "https://github.com/maxzz/real-time-resize-rcv",
        urlDemo: "https://codesandbox.io/s/github/maxzz/real-time-resize-rcv",
        previewUrl: images.realTimeResizeRcv,
        localPath: "https://codesandbox.io/s/github/maxzz/real-time-resize-rcv",
    },
    {
        caption: "react-sm",
        description: "React state management flavors.",
        urlGithub: "https://github.com/maxzz/react-sm",
        urlDemo: "https://maxzz.github.io/react-sm",
        previewUrl: images.reactSm,
        localPath: "C:/Y/w/2-web/1-frameworks/1-react/react-state-management-flavours",
    },
    {
        caption: "blooming-gen",
        description: "Blooming generator experiments.",
        urlGithub: "https://github.com/maxzz/blooming-gen",
        urlDemo: "https://maxzz.github.io/blooming-gen",
        previewUrl: images.bloomingGen,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/blooming-gen",
    },
    {
        caption: "giffy",
        description: "Experimenting with CSS Masonry Grid using the simple Giphy client.",
        urlGithub: "https://github.com/maxzz/giffy",
        urlDemo: "https://maxzz.github.io/giffy",
        previewUrl: images.giffy,
        localPath: "C:/Y/w/2-web/7-my-webpages/tests-react/giffy",
    },
];

export const projectsNpm: ProjectType[] = [
    {
        caption: "work-weeks",
        description: "Utility to generate working weeks per year.",
        urlGithub: "https://github.com/maxzz/work-weeks",
        urlDemo: "https://www.npmjs.com/package/work-weeks",
        previewUrl: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/work-weeks-calendar",
    },
    {
        caption: "rardir",
        description: "Utility to pack meta data inside specified folders.",
        urlGithub: "https://github.com/maxzz/rardir",
        urlDemo: "https://www.npmjs.com/package/rardir",
        previewUrl: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/rardir",
    },
    {
        caption: "rarsrt",
        description: "Utility to combine .SRT subtitles with .MP4 files inside specified folders.",
        urlGithub: "https://github.com/maxzz/rarsrt",
        urlDemo: "https://www.npmjs.com/package/rarsrt",
        previewUrl: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/merge-video-subtitles",
    },
    {
        caption: "spawn-loading-test",
        description: "Node.js test with spawning child processes and a control panel via a web interface.",
        urlGithub: "https://github.com/maxzz/spawn-loading-test",
        urlDemo: "https://github.com/maxzz/spawn-loading-test", // no demo
        previewUrl: images.spawnLoadingTest,
        localPath: "C:/Y/w/1-node/1-utils/spawn-loading-test",
    },
    {
        caption: "server-ocr",
        description: "Explore the Tesseract OCR engine.",
        urlGithub: "https://github.com/maxzz/server-ocr",
        urlDemo: "https://github.com/maxzz/server-ocr", // no demo
        previewUrl: images.serverOcr,
        localPath: "C:/Y/w/2-web/7-my-webpages/server-ocr",
    },
];

export const projectsVue: ProjectType[] = [
    {
        caption: "animated-sidebar",
        description: "Animated sidebar with Vue.js 3, TailwindCSS/Jit, and Vite.",
        urlGithub: "https://github.com/maxzz/animated-sidebar",
        urlDemo: "https://maxzz.github.io/animated-sidebar",
        previewUrl: images.animatedSidebar,
        localPath: "C:/Y/w/2-web/8-websites-ideas/3-vue/animated-sidebar",
        stack: ["vue", "tailwindcss"],
    },
    {
        caption: "ch-spy",
        description: "Web scrapping video links.",
        urlGithub: "https://github.com/maxzz/ch-spy",
        urlDemo: "https://maxzz.github.io/ch-spy",
        previewUrl: images.chSpy,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/coursehunters-course-list-browser",
        stack: ["vue", "tailwindcss"],
    },
    {
        caption: "coursehunters-course-list-browser-ctx",
        description: "The script can be embedded in the content of the page with the AddJS extension.",
        urlGithub: "https://github.com/maxzz/ch-spy-ext",
        urlDemo: "https://maxzz.github.io/ch-spy",
        previewUrl: images.coursehuntersCourseListBrowserCtx,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/coursehunters-course-list-browser-ctx",
    },
    {
        caption: "site-egghead.io-ctx",
        description: "Content script to embed in egghead.io with AddJs extension.",
        urlGithub: "https://github.com/maxzz/site-egghead.io-ctx",
        urlDemo: "https://maxzz.github.io/ch-spy",
        previewUrl: images.chSpy,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/site-egghead.io-ctx",
    },
    {
        caption: "auto-dat-gui",
        description: "dat-gui replica in Vue 3",
        urlGithub: "https://github.com/maxzz/auto-dat-gui",
        urlDemo: "https://maxzz.github.io/auto-dat-gui",
        previewUrl: images.autoDatGui,
        localPath: "C:/Y/w/2-web/2-generators/auto-dat-gui",
    },
    {
        caption: "back-to-90s-html",
        description: "A quick and easy project to keep old memories alive.",
        urlGithub: "https://github.com/maxzz/back-to-90s-html",
        urlDemo: "https://maxzz.github.io/back-to-90s-html",
        previewUrl: images.backTo90sHtml,
        localPath: "C:/Y/w/2-web/7-my-webpages/back-to-90s-html",
    },
    {
        caption: "vue-evens-todos",
        description: "This is an integration test with codesandbox.io. Created with CodeSandbox.",
        urlGithub: "https://github.com/maxzz/vue-evens-todos",
        urlDemo: "https://codesandbox.io/s/github/maxzz/vue-evens-todos",
        previewUrl: images.vue26SiteExamplesTodos,
        localPath: "C:/Y/w/2-web/7-my-webpages/vue-examples/vue26-site-examples-todos",
    },
];

export const sections: SectionType[] = [
    {
        name: 'UX',
        projects: projectsUx,
    },
    {
        name: 'DigitalPersona',
        projects: projectsDp,
    },
    {
        name: 'npm',
        projects: projectsNpm,
    },
    {
        name: 'Vue',
        projects: projectsVue,
    },
];
