import { ProjectType, SectionType } from "./store-types";
import * as images from "./store-images";

export const projectsDp: ProjectType[] = [
    {
        primary: 'DP',
        id: "page-qa2",
        description: "QA information website",
        urlGithub: "https://github.com/maxzz/page-qa2",
        urlDemo: "https://maxzz.github.io/page-qa2",
        urlPreview: images.pageQa2,
        localPath: "C:/Y/w/2-web/0-dp/page-qa2",
        stack: ['react', 'jotai', 'tw'],
    },
    {
        primary: 'DP',
        id: "PMIT",
        description: "Password manager investigation tool as an experiment with data-driven user interfaces (D2UI).",
        urlGithub: "https://github.com/maxzz/dropzone",
        urlDemo: "https://maxzz.github.io/dropzone",
        urlPreview: images.previewDropzon,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/dropzone",
        stack: ['react', 'jotai', 'tw'],
    },
    {
        primary: 'DP',
        id: "page-extension-installation",
        description: "Page for installing the DigitalPersona extension.",
        urlGithub: "https://github.com/maxzz/page-extension-installation",
        urlDemo: "https://maxzz.github.io/page-extension-installation",
        urlPreview: images.pageExtensionInstallation,
        localPath: "C:/Y/w/2-web/0-dp/page-extension-installation",
        stack: ['react', 'jotai', 'tw'],
    },
    {
        primary: 'DP',
        id: "test-pm",
        description: "Dynamic webpage to test Password Manager login and password change screens.",
        urlGithub: "https://github.com/maxzz/test-pm",
        urlDemo: "https://maxzz.github.io/test-pm",
        urlPreview: images.testPm,
        localPath: "C:/Y/w/2-web/0-dp/test-pm",
        stack: ['vue', 'css'],
    },
    {
        primary: 'DP',
        id: "test-pm-second",
        description: "Second page for checking logins on the same domain.",
        urlGithub: "https://github.com/maxzz/test-pm-second",
        urlDemo: "https://maxzz.github.io/test-pm-second",
        urlPreview: images.testPmSecond,
        localPath: "C:/Y/w/2-web/0-dp/test-pm-second",
        stack: ['react', 'jotai', 'tw'],
    },
    {
        primary: 'DP',
        id: "test-pm-domain-logins",
        description: "Test multiple logins under the same domain.",
        urlGithub: "https://github.com/maxzz/test-pm-domain-logins",
        urlDemo: "https://maxzz.github.io/test-pm-domain-logins/",
        urlPreview: images.testPmDomainLogins,
        localPath: "C:/Y/w/2-web/0-dp/test-pm-domain-logins",
        stack: ['vue', 'css'],
    },
    {
        primary: 'DP',
        id: "test-pm-domain-logins22",
        description: "Application for testing different login forms and password change in one domain.",
        urlGithub: "https://github.com/maxzz/test-pm-domain-logins22",
        urlDemo: "https://maxzz.github.io/test-pm-domain-logins22",
        urlPreview: images.testPmDomainLogins22,
        localPath: "C:/Y/w/2-web/0-dp/test-pm-domain-logins22",
        stack: ['react', 'jotai', 'tw'],
    },

    // {
    //     primary: 'DP',
    //     caption: "",
    //     description: "",
    //     urlGithub: "",
    //     urlDemo: "",
    //     previewUrl: images.editorsSvgShapes22Template,
    //     localPath: "",
    // },
];

export const projectsUx: ProjectType[] = [
    {
        primary: 'UX',
        id: "color-names22",
        description: "CSS color names selector",
        urlGithub: "https://github.com/maxzz/color-names22",
        urlDemo: "https://maxzz.github.io/color-names22",
        urlPreview: images.colorNames22,
        localPath: "C:/Y/w/2-web/7-my-webpages/color-names22",
        stack: ["react", "jotai", "tw"],
    },
    {
        primary: 'UX',
        id: "simple-border-radius22",
        description: "CSS border radius generator",
        urlGithub: "https://github.com/maxzz/simple-border-radius22",
        urlDemo: "https://maxzz.github.io/simple-border-radius22",
        urlPreview: images.simpleBorderRadius,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-border-radius22",
    },
    {
        primary: 'UX',
        id: "border-radius-generator",
        description: "Simplest border radius generator with Vue.js Composition API",
        urlGithub: "https://github.com/maxzz/border-radius-generator",
        urlDemo: "https://maxzz.github.io/border-radius-generator",
        urlPreview: images.borderRadiusGenerator,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-border-radius",
    },
    {
        primary: 'UX',
        id: "red3-curves",
        description: "Examination of the curves D3",
        urlGithub: "https://github.com/maxzz/red3-curves",
        urlDemo: "https://maxzz.github.io/red3-curves",
        urlPreview: images.red3Curves,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-lines",
    },
    {
        primary: 'UX',
        id: "red3-path",
        description: "Curve path simplification",
        urlGithub: "https://github.com/maxzz/red3-path",
        urlDemo: "https://maxzz.github.io/red3-path",
        urlPreview: images.red3Path,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-path",
    },
    {
        primary: 'UX',
        id: "red3-voronoi",
        description: "Voronoi algorithm playground",
        urlGithub: "https://github.com/maxzz/red3-voronoi",
        urlDemo: "https://maxzz.github.io/red3-voronoi",
        urlPreview: images.reactD3Voronoi,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-voronoi",
    },
    {
        primary: 'UX',
        id: "react-d3",
        description: "Coexistence of React with D3.js",
        urlGithub: "https://github.com/maxzz/react-d3",
        urlDemo: "https://maxzz.github.io/react-d3",
        urlPreview: images.reactD3,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-red3",
    },
    {
        primary: 'UX',
        id: "svg-path",
        description: "SVG path exploration",
        urlGithub: "https://github.com/maxzz/svg-path",
        urlDemo: "https://maxzz.github.io/svg-path",
        urlPreview: images.svgPath,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/svg-path",
    },
    {
        primary: 'UX',
        id: "quadratic-curves",
        description: "Quadratic curves experiments.",
        urlGithub: "https://github.com/maxzz/quadratic-curves",
        urlDemo: "https://github.com/maxzz/quadratic-curves", // no demo
        urlPreview: images.quadraticCurves,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-bezier/quadratic",
    },
    {
        primary: 'UX',
        id: "ngon-gen22",
        description: "N-gon generator.",
        urlGithub: "https://github.com/maxzz/ngon-gen22",
        urlDemo: "https://maxzz.github.io/ngon-gen22",
        urlPreview: images.ngonGen22,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes22",
    },
    {
        primary: 'UX',
        id: "ngon-gen22-template",
        description: "Template for React, Jotai, TailwindCSS app",
        urlGithub: "https://github.com/maxzz/ngon-gen22-template",
        urlDemo: "https://maxzz.github.io/ngon-gen22",
        urlPreview: images.editorsSvgShapes22Template,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes22-template",
    },
    {
        primary: 'UX',
        id: "cursors",
        description: "Web Cursors Lab",
        urlGithub: "https://github.com/maxzz/cursors",
        urlDemo: "https://maxzz.github.io/cursors",
        urlPreview: images.cursors,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/2-image-processing/cursors",
    },
    {
        primary: 'UX',
        id: "noise-gen",
        description: "Noise generator",
        urlGithub: "https://github.com/maxzz/noise-gen",
        urlDemo: "https://maxzz.github.io/noise-gen",
        urlPreview: images.noiseGen,
        localPath: "C:/Y/w/2-web/7-my-webpages/webworker-noise-gen",
    },
    {
        primary: 'UX',
        id: "css-3d",
        description: "Experimanting with pseudo-3D shapes.",
        urlGithub: "https://github.com/maxzz/css-3d",
        urlDemo: "https://maxzz.github.io/css-3d",
        urlPreview: images.css3d,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-css-3d",
    },
    {
        primary: 'UX',
        id: "react-spring-tests",
        description: "Exploring different use cases for the react-spring library.",
        urlGithub: "https://github.com/maxzz/react-spring-tests",
        urlDemo: "https://maxzz.github.io/react-spring-tests",
        urlPreview: images.reactSpringTests,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/1-animations/react-spring-tests",
    },

    {
        primary: 'UX',
        id: "leva-ui-dynamic-boxes",
        description: "Experimenting with box resizing handles using leva and zustand.",
        urlGithub: "https://github.com/maxzz/leva-ui-dynamic-boxes",
        urlDemo: "https://maxzz.github.io/leva-ui-dynamic-boxes",
        urlPreview: images.levaUiDynamicBoxes,
        localPath: "C:/Y/w/2-web/7-my-webpages/leva-ui-dynamic-boxes",
    },
    {
        primary: 'UX',
        id: "volume-illusion",
        description: "Illusion of three-dimensional shapes.",
        urlGithub: "https://github.com/maxzz/volume-illusion",
        urlDemo: "https://maxzz.github.io/volume-illusion",
        urlPreview: images.volumeIllusion,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-volume-illusion",
    },
    {
        primary: 'UX',
        id: "real-time-resize-rcv",
        description: "Created with CodeSandbox. Virtual lists.",
        urlGithub: "https://github.com/maxzz/real-time-resize-rcv",
        urlDemo: "https://codesandbox.io/s/github/maxzz/real-time-resize-rcv",
        urlPreview: images.realTimeResizeRcv,
        localPath: "https://codesandbox.io/s/github/maxzz/real-time-resize-rcv",
    },
    {
        primary: 'UX',
        id: "react-sm",
        description: "React state management flavors.",
        urlGithub: "https://github.com/maxzz/react-sm",
        urlDemo: "https://maxzz.github.io/react-sm",
        urlPreview: images.reactSm,
        localPath: "C:/Y/w/2-web/1-frameworks/1-react/react-state-management-flavours",
    },
    {
        primary: 'UX',
        id: "blooming-gen",
        description: "Blooming generator experiments.",
        urlGithub: "https://github.com/maxzz/blooming-gen",
        urlDemo: "https://maxzz.github.io/blooming-gen",
        urlPreview: images.bloomingGen,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/blooming-gen",
    },
    {
        primary: 'UX',
        id: "giffy",
        description: "Experimenting with CSS Masonry Grid using the simple Giphy client.",
        urlGithub: "https://github.com/maxzz/giffy",
        urlDemo: "https://maxzz.github.io/giffy",
        urlPreview: images.giffy,
        localPath: "C:/Y/w/2-web/7-my-webpages/tests-react/giffy",
    },
    {
        primary: 'UX',
        id: "react-focus-within-menus",
        description: "Study project: Exploring UX of the menu interactions.",
        urlGithub: "https://github.com/maxzz/react-focus-within-menus",
        urlDemo: "https://maxzz.github.io/react-focus-within-menus",
        urlPreview: images.reactFocusWithinMenus,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/fluid-menu-links",
    },
    {
        primary: 'UX',
        id: "react-gsap-menu",
        description: "Menu with SVG animated blobs",
        urlGithub: "https://github.com/maxzz/react-gsap-menu",
        urlDemo: "https://maxzz.github.io/react-gsap-menu",
        urlPreview: images.reactGsapMenu,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/react-gsap-menu",
    },
    {
        primary: 'UX',
        id: "react-spring-interpolation",
        description: "Shapes interpolation with react-spring.",
        urlGithub: "https://github.com/maxzz/react-spring-interpolation",
        urlDemo: "https://maxzz.github.io/react-spring-interpolation",
        urlPreview: images.reactSpringInterpolation,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/sprint-interpolation",
    },
    {
        primary: 'UX',
        id: "react-delay-unmount",
        description: "Investigation of the possibility of animating components when mounting / unmounting.",
        urlGithub: "https://github.com/maxzz/react-delay-unmount",
        urlDemo: "https://maxzz.github.io/react-delay-unmount",
        urlPreview: images.reactDelayUnmount,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/delay-unmount",
    },
    {
        primary: 'UX',
        id: "react-scrolling-carousel",
        description: "Carousel React Component with scrolling.",
        urlGithub: "https://github.com/maxzz/react-scrolling-carousel",
        urlDemo: "https://maxzz.github.io/react-scrolling-carousel",
        urlPreview: images.reactScrollingCarousel,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/scroller",
    },
    {
        primary: 'UX',
        id: "svg-icons-font-sw",
        description: "My learning and experimenting with custom SVG fonts.",
        urlGithub: "https://github.com/maxzz/svg-icons-font-sw",
        urlDemo: "https://maxzz.github.io/svg-icons-font-sw",
        urlPreview: images.svgIconsFontSw,
        localPath: "C:/Y/w/2-web/7-my-webpages/svg-icons-font-sw",
        stack: ["js"]
    },
    {
        primary: 'UX',
        id: "react-admin-address-book",
        description: "Address book using react-admin framework.",
        urlGithub: "https://github.com/maxzz/react-admin-address-book",
        urlDemo: "https://maxzz.github.io/react-admin-address-book",
        urlPreview: images.reactAdminAddressBook,
        localPath: "C:/Y/w/2-web/1-frameworks/1-react/react-admin-address-book",
    },
    {
        primary: 'UX',
        id: "react-lifecycles",
        description: "React life cycles trace",
        urlGithub: "https://github.com/maxzz/react-lifecycles",
        urlDemo: "https://github.com/maxzz/react-lifecycles", // no demo
        urlPreview: images.reactNoPreview,
        localPath: "C:/Y/w/2-web/7-my-webpages/tests-react/react-lifecycles",
    },
    {
        primary: 'UX',
        id: "maxzz",
        description: "maxzz/maxzz is a special repository. This README.md will appear on your public profile.",
        urlGithub: "https://github.com/maxzz/maxzz",
        urlDemo: "https://github.com/maxzz",
        urlPreview: images.maxzz,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-frontpage",
    },
    {
        primary: 'UX',
        id: "maxzz.github.io",
        description: "Mirror image of this page on GitHub",
        urlGithub: "https://github.com/maxzz/maxzz.github.io",
        urlDemo: "https://maxzz.github.io",
        urlPreview: images.maxzzGithubIo,
        localPath: "C:/Y/w/2-web/7-my-webpages/maxzz",
    },
];

export const projectsNpm: ProjectType[] = [
    {
        primary: 'npm',
        id: "work-weeks",
        description: "Utility to generate working weeks per year.",
        urlGithub: "https://github.com/maxzz/work-weeks",
        urlDemo: "https://www.npmjs.com/package/work-weeks",
        urlPreview: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/work-weeks-calendar",
        stack: ['npm'],
    },
    {
        primary: 'npm',
        id: "rardir",
        description: "Utility to pack meta data inside specified folders.",
        urlGithub: "https://github.com/maxzz/rardir",
        urlDemo: "https://www.npmjs.com/package/rardir",
        urlPreview: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/rardir",
    },
    {
        primary: 'npm',
        id: "rarsrt",
        description: "Utility to combine .SRT subtitles with .MP4 files inside specified folders.",
        urlGithub: "https://github.com/maxzz/rarsrt",
        urlDemo: "https://www.npmjs.com/package/rarsrt",
        urlPreview: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/merge-video-subtitles",
    },
    {
        primary: 'npm',
        id: "spawn-loading-test",
        description: "Node.js test with spawning child processes and a control panel via a web interface.",
        urlGithub: "https://github.com/maxzz/spawn-loading-test",
        urlDemo: "https://github.com/maxzz/spawn-loading-test", // no demo
        urlPreview: images.spawnLoadingTest,
        localPath: "C:/Y/w/1-node/1-utils/spawn-loading-test",
    },
    {
        primary: 'npm',
        id: "server-ocr",
        description: "Explore the Tesseract OCR engine.",
        urlGithub: "https://github.com/maxzz/server-ocr",
        urlDemo: "https://github.com/maxzz/server-ocr", // no demo
        urlPreview: images.serverOcr,
        localPath: "C:/Y/w/2-web/7-my-webpages/server-ocr",
        stack: ['npm', 'js'],
    },
    {
        primary: 'npm',
        id: "test-graphql",
        description: "GraphQL server test implementation.",
        urlGithub: "https://github.com/maxzz/test-graphql",
        urlDemo: "https://github.com/maxzz/test-graphql", // no demo
        urlPreview: images.npm,
        localPath: "C:/Y/w/2-web/7-my-webpages/test-graphql",
    },
    {
        primary: 'npm',
        id: "gluehtml",
        description: "Glue HTML local external files into solid HTML.",
        urlGithub: "https://www.npmjs.com/package/gluehtml",
        urlDemo: "https://www.npmjs.com/package/gluehtml",
        urlPreview: images.gluehtml,
        localPath: "C:/Y/w/1-node/1-utils/create-single-html",
    },
    {
        primary: 'npm',
        id: "netsh-rule",
        description: "Utility to generate a batch file to manage inbound and outbound Windows firewall connections for a single .exe file or all .exe files in folder.",
        urlGithub: "https://github.com/maxzz/netsh-rule",
        urlDemo: "https://www.npmjs.com/package/netsh-rule",
        urlPreview: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/netsh-firewall-rules",
    },
    {
        primary: 'npm',
        id: "pm-domain-credentials-switch",
        description: "Utility to convert PM domain credentials to credentials that only apply to the exact URL.",
        urlGithub: "https://github.com/maxzz/pm-domain-credentials-switch",
        urlDemo: "https://github.com/maxzz/pm-domain-credentials-switch", // no demo
        urlPreview: images.npm,
        localPath: "C:/Y/w/2-web/0-dp/utils/pm-domain-credentials-switch",
        stack: ['npm'],
    },
    {
        primary: 'npm',
        id: "maxzz-proxy",
        description: "Proxy server with CORS.",
        urlGithub: "https://github.com/maxzz/maxzz-proxy",
        urlDemo: "https://github.com/maxzz/maxzz-proxy", // no demo
        urlPreview: images.npm,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/maxzz-proxy",
    },
    {
        primary: 'npm',
        id: "maxzz-python",
        description: "Creating GitHub frontpage readme.md file with Python.",
        urlGithub: "https://github.com/maxzz/maxzz-python",
        urlDemo: "https://github.com/maxzz/maxzz-python", // no demo
        urlPreview: images.npm,
        localPath: "cannot find the local project anymore",
    },
];

export const projectsVue: ProjectType[] = [
    {
        primary: 'vue',
        id: "color-names",
        description: "CSS color names playground",
        urlGithub: "https://github.com/maxzz/color-names",
        urlDemo: "https://maxzz.github.io/color-names",
        urlPreview: images.colorNames,
        localPath: "C:/Y/w/2-web/7-my-webpages/color-names",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "ngon-gen",
        description: "n-gon SVG generator.",
        urlGithub: "https://github.com/maxzz/ngon-gen",
        urlDemo: "https://maxzz.github.io/ngon-gen",
        urlPreview: images.ngonGen,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "animated-sidebar",
        description: "Animated sidebar with Vue.js 3, TailwindCSS/Jit, and Vite.",
        urlGithub: "https://github.com/maxzz/animated-sidebar",
        urlDemo: "https://maxzz.github.io/animated-sidebar",
        urlPreview: images.animatedSidebar,
        localPath: "C:/Y/w/2-web/8-websites-ideas/3-vue/animated-sidebar",
        stack: ["vue", "tw"],
    },
    {
        primary: 'vue',
        id: "ch-spy",
        description: "Web scrapping video links.",
        urlGithub: "https://github.com/maxzz/ch-spy",
        urlDemo: "https://maxzz.github.io/ch-spy",
        urlPreview: images.chSpy,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/coursehunters-course-list-browser",
        stack: ["vue", "tw"],
    },
    {
        primary: 'vue',
        id: "coursehunters-course-list-browser-ctx",
        description: "The script can be embedded in the content of the page with the AddJS extension.",
        urlGithub: "https://github.com/maxzz/ch-spy-ext",
        urlDemo: "https://maxzz.github.io/ch-spy",
        urlPreview: images.coursehuntersCourseListBrowserCtx,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/coursehunters-course-list-browser-ctx",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "site-egghead.io-ctx",
        description: "Content script to embed in egghead.io with AddJs extension.",
        urlGithub: "https://github.com/maxzz/site-egghead.io-ctx",
        urlDemo: "https://maxzz.github.io/ch-spy",
        urlPreview: images.chSpy,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/site-egghead.io-ctx",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "auto-dat-gui",
        description: "dat-gui replica in Vue 3",
        urlGithub: "https://github.com/maxzz/auto-dat-gui",
        urlDemo: "https://maxzz.github.io/auto-dat-gui",
        urlPreview: images.autoDatGui,
        localPath: "C:/Y/w/2-web/2-generators/auto-dat-gui",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "back-to-90s-html",
        description: "A quick and easy project to keep old memories alive.",
        urlGithub: "https://github.com/maxzz/back-to-90s-html",
        urlDemo: "https://maxzz.github.io/back-to-90s-html",
        urlPreview: images.backTo90sHtml,
        localPath: "C:/Y/w/2-web/7-my-webpages/back-to-90s-html",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "vue-evens-todos",
        description: "This is an integration test with codesandbox.io. Created with CodeSandbox.",
        urlGithub: "https://github.com/maxzz/vue-evens-todos",
        urlDemo: "https://codesandbox.io/s/github/maxzz/vue-evens-todos",
        urlPreview: images.vue26SiteExamplesTodos,
        localPath: "C:/Y/w/2-web/7-my-webpages/vue-examples/vue26-site-examples-todos",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "svg-gradients",
        description: "Exploring SVG Gradients.",
        urlGithub: "https://github.com/maxzz/svg-gradients",
        urlDemo: "https://maxzz.github.io/svg-gradients",
        urlPreview: images.svgGradients,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-gradients",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "revue-playground",
        description: "AST in the ESTree format playground.",
        urlGithub: "https://github.com/maxzz/revue-playground",
        urlDemo: "https://maxzz.github.io/revue-playground/",
        urlPreview: images.revuePlayground,
        localPath: "C:/Y/w/1-node/1-utils/reverse-vue-render",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "svg-icons-vite",
        description: "Vite + SVG icons experiment.",
        urlGithub: "https://github.com/maxzz/svg-icons-vite",
        urlDemo: "https://maxzz.github.io/svg-icons-vite",
        urlPreview: images.svgIconsVite,
        localPath: "C:/Y/w/2-web/7-my-webpages/svg-icons-vite",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "simple-siriwave",
        description: "This project is a simple wrapper for the wave control using the Vue composition API.",
        urlGithub: "https://github.com/maxzz/simple-siriwave",
        urlDemo: "https://maxzz.github.io/simple-siriwave",
        urlPreview: images.simpleSiriwave,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-siriwave",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "svg-bkg-stripes",
        description: "SVG generation playground.",
        urlGithub: "https://github.com/maxzz/svg-bkg-stripes",
        urlDemo: "https://maxzz.github.io/svg-bkg-stripes",
        urlPreview: images.svgBkgStripes,
        localPath: "C:/Y/w/2-web/2-generators/svg-bkg-stripes",
        stack: ['vue'],
    },
];

export const sections: SectionType[] = [
    {
        name: 'UX',
        projects: projectsUx,
    },
    {
        name: 'DigitalPersona',
        projects: projectsDp,
    },
    {
        name: 'npm',
        projects: projectsNpm,
    },
    {
        name: 'Vue',
        projects: projectsVue,
    },
];

//TODO: add C:\Y\w\2-web\0-dp\utils\sftp-shell
//TODO: add C:\Y\w\2-web\0-dp\utils\sftp-test
