import { ProjectType, SectionType } from "../store-types";
import * as images from "../../assets/pages/react/store-images";

export const projectsUx: ProjectType[] = [
    {
        primary: 'UX',
        id: "color-names22",
        description: "CSS color names selector",
        urlGithub: "https://github.com/maxzz/color-names22",
        urlDemo: "https://maxzz.github.io/color-names22",
        urlPreview: images.colorNames22,
        localPath: "C:/Y/w/2-web/7-my-webpages/color-names22",
        stack: ["react", "jotai", "tw"],
    },
    {
        primary: 'UX',
        id: "simple-border-radius22",
        description: "CSS border radius generator",
        urlGithub: "https://github.com/maxzz/simple-border-radius22",
        urlDemo: "https://maxzz.github.io/simple-border-radius22",
        urlPreview: images.simpleBorderRadius,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-border-radius22",
    },
    {
        primary: 'UX',
        id: "border-radius-generator",
        description: "Simplest border radius generator with Vue.js Composition API",
        urlGithub: "https://github.com/maxzz/border-radius-generator",
        urlDemo: "https://maxzz.github.io/border-radius-generator",
        urlPreview: images.borderRadiusGenerator,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-border-radius",
    },
    {
        primary: 'UX',
        id: "red3-curves",
        description: "Examination of the curves D3",
        urlGithub: "https://github.com/maxzz/red3-curves",
        urlDemo: "https://maxzz.github.io/red3-curves",
        urlPreview: images.red3Curves,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-lines",
    },
    {
        primary: 'UX',
        id: "red3-path",
        description: "Curve path simplification",
        urlGithub: "https://github.com/maxzz/red3-path",
        urlDemo: "https://maxzz.github.io/red3-path",
        urlPreview: images.red3Path,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-path",
    },
    {
        primary: 'UX',
        id: "red3-voronoi",
        description: "Voronoi algorithm playground",
        urlGithub: "https://github.com/maxzz/red3-voronoi",
        urlDemo: "https://maxzz.github.io/red3-voronoi",
        urlPreview: images.reactD3Voronoi,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-voronoi",
    },
    {
        primary: 'UX',
        id: "react-d3",
        description: "Coexistence of React with D3.js",
        urlGithub: "https://github.com/maxzz/react-d3",
        urlDemo: "https://maxzz.github.io/react-d3",
        urlPreview: images.reactD3,
        localPath: "C:/Y/w/2-web/1-frameworks/5-d3/react-d3-red3",
    },
    {
        primary: 'UX',
        id: "svg-path",
        description: "SVG path exploration",
        urlGithub: "https://github.com/maxzz/svg-path",
        urlDemo: "https://maxzz.github.io/svg-path",
        urlPreview: images.svgPath,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/svg-path",
    },
    {
        primary: 'UX',
        id: "quadratic-curves",
        description: "Quadratic curves experiments.",
        urlGithub: "https://github.com/maxzz/quadratic-curves",
        urlDemo: "https://maxzz.github.io/quadratic-curves",
        urlPreview: images.quadraticCurves,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-bezier/quadratic",
        stack: ['ts', 'tw'],
    },
    {
        primary: 'UX',
        id: "ngon-gen22",
        description: "N-gon generator.",
        urlGithub: "https://github.com/maxzz/ngon-gen22",
        urlDemo: "https://maxzz.github.io/ngon-gen22",
        urlPreview: images.ngonGen22,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes22",
    },
    {
        primary: 'UX',
        id: "ngon-gen22-template",
        description: "Template for React, Jotai, TailwindCSS app",
        urlGithub: "https://github.com/maxzz/ngon-gen22-template",
        urlDemo: "https://maxzz.github.io/ngon-gen22",
        urlPreview: images.editorsSvgShapes22Template,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes22-template",
    },
    {
        primary: 'UX',
        id: "cursors",
        description: "Web Cursors Lab",
        urlGithub: "https://github.com/maxzz/cursors",
        urlDemo: "https://maxzz.github.io/cursors",
        urlPreview: images.cursors,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/2-image-processing/cursors",
    },
    {
        primary: 'UX',
        id: "noise-gen",
        description: "Noise generator",
        urlGithub: "https://github.com/maxzz/noise-gen",
        urlDemo: "https://maxzz.github.io/noise-gen",
        urlPreview: images.noiseGen,
        localPath: "C:/Y/w/2-web/7-my-webpages/webworker-noise-gen",
    },
    {
        primary: 'UX',
        id: "css-3d",
        description: "Experimanting with pseudo-3D shapes.",
        urlGithub: "https://github.com/maxzz/css-3d",
        urlDemo: "https://maxzz.github.io/css-3d",
        urlPreview: images.css3d,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-css-3d",
    },
    {
        primary: 'UX',
        id: "react-spring-tests",
        description: "Exploring different use cases for the react-spring library.",
        urlGithub: "https://github.com/maxzz/react-spring-tests",
        urlDemo: "https://maxzz.github.io/react-spring-tests",
        urlPreview: images.reactSpringTests,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/1-animations/react-spring-tests",
    },

    {
        primary: 'UX',
        id: "leva-ui-dynamic-boxes",
        description: "Experimenting with box resizing handles using leva and zustand.",
        urlGithub: "https://github.com/maxzz/leva-ui-dynamic-boxes",
        urlDemo: "https://maxzz.github.io/leva-ui-dynamic-boxes",
        urlPreview: images.levaUiDynamicBoxes,
        localPath: "C:/Y/w/2-web/7-my-webpages/leva-ui-dynamic-boxes",
    },
    {
        primary: 'UX',
        id: "volume-illusion",
        description: "Illusion of three-dimensional shapes.",
        urlGithub: "https://github.com/maxzz/volume-illusion",
        urlDemo: "https://maxzz.github.io/volume-illusion",
        urlPreview: images.volumeIllusion,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-volume-illusion",
    },
    {
        primary: 'UX',
        id: "real-time-resize-rcv",
        description: "Created with CodeSandbox. Virtual lists.",
        urlGithub: "https://github.com/maxzz/real-time-resize-rcv",
        urlDemo: "https://codesandbox.io/s/github/maxzz/real-time-resize-rcv",
        urlPreview: images.realTimeResizeRcv,
        localPath: "https://codesandbox.io/s/github/maxzz/real-time-resize-rcv",
    },
    {
        primary: 'UX',
        id: "react-sm",
        description: "React state management flavors.",
        urlGithub: "https://github.com/maxzz/react-sm",
        urlDemo: "https://maxzz.github.io/react-sm",
        urlPreview: images.reactSm,
        localPath: "C:/Y/w/2-web/1-frameworks/1-react/react-state-management-flavours",
    },
    {
        primary: 'UX',
        id: "blooming-gen",
        description: "Blooming generator experiments.",
        urlGithub: "https://github.com/maxzz/blooming-gen",
        urlDemo: "https://maxzz.github.io/blooming-gen",
        urlPreview: images.bloomingGen,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/blooming-gen",
    },
    {
        primary: 'UX',
        id: "giffy",
        description: "Experimenting with CSS Masonry Grid using the simple Giphy client.",
        urlGithub: "https://github.com/maxzz/giffy",
        urlDemo: "https://maxzz.github.io/giffy",
        urlPreview: images.giffy,
        localPath: "C:/Y/w/2-web/7-my-webpages/tests-react/giffy",
    },
    {
        primary: 'UX',
        id: "react-focus-within-menus",
        description: "Study project: Exploring UX of the menu interactions.",
        urlGithub: "https://github.com/maxzz/react-focus-within-menus",
        urlDemo: "https://maxzz.github.io/react-focus-within-menus",
        urlPreview: images.reactFocusWithinMenus,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/fluid-menu-links",
    },
    {
        primary: 'UX',
        id: "react-gsap-menu",
        description: "Menu with SVG animated blobs",
        urlGithub: "https://github.com/maxzz/react-gsap-menu",
        urlDemo: "https://maxzz.github.io/react-gsap-menu",
        urlPreview: images.reactGsapMenu,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/react-gsap-menu",
    },
    {
        primary: 'UX',
        id: "react-spring-interpolation",
        description: "Shapes interpolation with react-spring.",
        urlGithub: "https://github.com/maxzz/react-spring-interpolation",
        urlDemo: "https://maxzz.github.io/react-spring-interpolation",
        urlPreview: images.reactSpringInterpolation,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/sprint-interpolation",
    },
    {
        primary: 'UX',
        id: "react-delay-unmount",
        description: "Investigation of the possibility of animating components when mounting / unmounting.",
        urlGithub: "https://github.com/maxzz/react-delay-unmount",
        urlDemo: "https://maxzz.github.io/react-delay-unmount",
        urlPreview: images.reactDelayUnmount,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/delay-unmount",
    },
    {
        primary: 'UX',
        id: "react-scrolling-carousel",
        description: "Carousel React Component with scrolling.",
        urlGithub: "https://github.com/maxzz/react-scrolling-carousel",
        urlDemo: "https://maxzz.github.io/react-scrolling-carousel",
        urlPreview: images.reactScrollingCarousel,
        localPath: "C:/Y/w/2-web/8-websites-ideas/4-react/scroller",
    },
    {
        primary: 'UX',
        id: "svg-icons-font-sw",
        description: "My learning and experimenting with custom SVG fonts.",
        urlGithub: "https://github.com/maxzz/svg-icons-font-sw",
        urlDemo: "https://maxzz.github.io/svg-icons-font-sw",
        urlPreview: images.svgIconsFontSw,
        localPath: "C:/Y/w/2-web/7-my-webpages/svg-icons-font-sw",
        stack: ["js"]
    },
    {
        primary: 'UX',
        id: "react-admin-address-book",
        description: "Address book using react-admin framework.",
        urlGithub: "https://github.com/maxzz/react-admin-address-book",
        urlDemo: "https://maxzz.github.io/react-admin-address-book",
        urlPreview: images.reactAdminAddressBook,
        localPath: "C:/Y/w/2-web/1-frameworks/1-react/react-admin-address-book",
    },
    {
        primary: 'UX',
        id: "react-lifecycles",
        description: "React life cycles trace",
        urlGithub: "https://github.com/maxzz/react-lifecycles",
        urlDemo: "https://github.com/maxzz/react-lifecycles", // no demo
        urlPreview: images.reactNoPreview,
        localPath: "C:/Y/w/2-web/7-my-webpages/tests-react/react-lifecycles",
    },
    {
        primary: 'UX',
        id: "maxzz",
        description: "maxzz/maxzz is a special repository. This README.md will appear on your public profile.",
        urlGithub: "https://github.com/maxzz/maxzz",
        urlDemo: "https://github.com/maxzz",
        urlPreview: images.maxzz,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-frontpage",
        stack: ['github', 'ts'],
    },
    {
        primary: 'UX',
        id: "maxzz.github.io",
        description: "Mirror image of this page on GitHub",
        urlGithub: "https://github.com/maxzz/maxzz.github.io",
        urlDemo: "https://maxzz.github.io",
        urlPreview: images.maxzzGithubIo,
        localPath: "C:/Y/w/2-web/7-my-webpages/maxzz",
        stack: ['github', 'ts'],
    },
];

