import { ProjectType } from "./store-types";
import * as images from "./store-images";

export const projectsVue: ProjectType[] = [
    {
        primary: 'vue',
        id: "color-names",
        description: "CSS color names playground",
        urlGithub: "https://github.com/maxzz/color-names",
        urlDemo: "https://maxzz.github.io/color-names",
        urlPreview: images.colorNames,
        localPath: "C:/Y/w/2-web/7-my-webpages/color-names",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "ngon-gen",
        description: "n-gon SVG generator.",
        urlGithub: "https://github.com/maxzz/ngon-gen",
        urlDemo: "https://maxzz.github.io/ngon-gen",
        urlPreview: images.ngonGen,
        localPath: "C:/Y/w/2-web/7-my-webpages/editors-svg-shapes",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "animated-sidebar",
        description: "Animated sidebar with Vue.js 3, TailwindCSS/Jit, and Vite.",
        urlGithub: "https://github.com/maxzz/animated-sidebar",
        urlDemo: "https://maxzz.github.io/animated-sidebar",
        urlPreview: images.animatedSidebar,
        localPath: "C:/Y/w/2-web/8-websites-ideas/3-vue/animated-sidebar",
        stack: ["vue", "tw"],
    },
    {
        primary: 'vue',
        id: "ch-spy",
        description: "Web scrapping video links.",
        urlGithub: "https://github.com/maxzz/ch-spy",
        urlDemo: "https://maxzz.github.io/ch-spy",
        urlPreview: images.chSpy,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/coursehunters-course-list-browser",
        stack: ["vue", "tw"],
    },
    {
        primary: 'vue',
        id: "coursehunters-course-list-browser-ctx",
        description: "The script can be embedded in the content of the page with the AddJS extension.",
        urlGithub: "https://github.com/maxzz/ch-spy-ext",
        urlDemo: "https://maxzz.github.io/ch-spy",
        urlPreview: images.coursehuntersCourseListBrowserCtx,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/coursehunters-course-list-browser-ctx",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "site-egghead.io-ctx",
        description: "Content script to embed in egghead.io with AddJs extension.",
        urlGithub: "https://github.com/maxzz/site-egghead.io-ctx",
        urlDemo: "https://maxzz.github.io/ch-spy",
        urlPreview: images.chSpy,
        localPath: "C:/Y/w/1-node/1-utils/1-web-scraping/site-egghead.io-ctx",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "auto-dat-gui",
        description: "dat-gui replica in Vue 3",
        urlGithub: "https://github.com/maxzz/auto-dat-gui",
        urlDemo: "https://maxzz.github.io/auto-dat-gui",
        urlPreview: images.autoDatGui,
        localPath: "C:/Y/w/2-web/2-generators/auto-dat-gui",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "back-to-90s-html",
        description: "A quick and easy project to keep old memories alive.",
        urlGithub: "https://github.com/maxzz/back-to-90s-html",
        urlDemo: "https://maxzz.github.io/back-to-90s-html",
        urlPreview: images.backTo90sHtml,
        localPath: "C:/Y/w/2-web/7-my-webpages/back-to-90s-html",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "vue-evens-todos",
        description: "This is an integration test with codesandbox.io. Created with CodeSandbox.",
        urlGithub: "https://github.com/maxzz/vue-evens-todos",
        urlDemo: "https://codesandbox.io/s/github/maxzz/vue-evens-todos",
        urlPreview: images.vue26SiteExamplesTodos,
        localPath: "C:/Y/w/2-web/7-my-webpages/vue-examples/vue26-site-examples-todos",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "svg-gradients",
        description: "Exploring SVG Gradients.",
        urlGithub: "https://github.com/maxzz/svg-gradients",
        urlDemo: "https://maxzz.github.io/svg-gradients",
        urlPreview: images.svgGradients,
        localPath: "C:/Y/w/2-web/7-my-webpages/github-gradients",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "revue-playground",
        description: "AST in the ESTree format playground.",
        urlGithub: "https://github.com/maxzz/revue-playground",
        urlDemo: "https://maxzz.github.io/revue-playground/",
        urlPreview: images.revuePlayground,
        localPath: "C:/Y/w/1-node/1-utils/reverse-vue-render",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "svg-icons-vite",
        description: "Vite + SVG icons experiment.",
        urlGithub: "https://github.com/maxzz/svg-icons-vite",
        urlDemo: "https://maxzz.github.io/svg-icons-vite",
        urlPreview: images.svgIconsVite,
        localPath: "C:/Y/w/2-web/7-my-webpages/svg-icons-vite",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "simple-siriwave",
        description: "This project is a simple wrapper for the wave control using the Vue composition API.",
        urlGithub: "https://github.com/maxzz/simple-siriwave",
        urlDemo: "https://maxzz.github.io/simple-siriwave",
        urlPreview: images.simpleSiriwave,
        localPath: "C:/Y/w/2-web/7-my-webpages/simple-siriwave",
        stack: ['vue'],
    },
    {
        primary: 'vue',
        id: "svg-bkg-stripes",
        description: "SVG generation playground.",
        urlGithub: "https://github.com/maxzz/svg-bkg-stripes",
        urlDemo: "https://maxzz.github.io/svg-bkg-stripes",
        urlPreview: images.svgBkgStripes,
        localPath: "C:/Y/w/2-web/2-generators/svg-bkg-stripes",
        stack: ['vue'],
    },
];
